<?php
/**
 * @file
 * Basic Functionality for the tripal germplasm module
 */

require_once 'includes/tripal_germplasm.chado_node.inc';
require_once 'includes/tripal_germplasm.admin.inc';
require_once 'includes/tripal_germplasm.parents_form.inc';
require_once 'includes/tripal_germplasm.cross_progeny_form.inc';

require_once 'api/tripal_germplasm.api.inc';

/**
 * Implements hook_menu().
 */
function tripal_germplasm_menu() {
  $items = array();

  $items['admin/tripal/extension/tripal_germplasm'] = array(
    'title' => 'Germplasm',
    'description' => 'Provides a germplasm content type which is a specialized version of a stock. Furthermore, functions, forms & views pertaining to managing a germplasm collection.',
    'page callback' => 'tripal_germplasm_admin_germplasm_listing',
    'access arguments' => array('administer tripal'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/tripal/extension/tripal_germplasm/help'] = array(
    'title' => 'Help',
    'description' => 'Basic Description of Tripal Germplasm Module Functionality',
    'page callback' => 'theme',
    'page arguments' => array('tripal_germplasm_help'),
    'access arguments' => array('administer tripal'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10
  );

  $items['admin/tripal/extension/tripal_germplasm/configuration'] = array(
    'title' => 'Settings',
    'description' => 'Configure the Tripal Germplasm module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tripal_germplasm_admin_settings_form'),
    'access arguments' => array('administer tripal'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 5
  );

  $items['admin/tripal/extension/tripal_germplasm/sync'] = array(
    'title' => ' Sync',
    'description' => 'Sync germplasm from Chado with Drupal',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chado_node_sync_form', 'tripal_germplasm', 'tripal_germplasm'),
    'access arguments' => array('administer tripal'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0
  );

  // Name autocomplete.
  $items['tripal_ajax/tripal_germplasm/name_to_id/%'] = array(
    'page callback' => 'tripal_germplasm_name_to_id_callback',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function tripal_germplasm_theme($existing, $type, $theme, $path) {
  $items = array();
  $core_path = drupal_get_path('module', 'tripal_core');

  $items['tripal_germplasm_help'] = array(
    'template' => 'tripal_germplasm.help',
    'variables' =>  array(NULL),
    'path' => "$path/theme",
  );

  $items['node__tripal_germplasm'] = array(
    'template' => 'node--chado-generic',
    'render element' => 'node',
    'base hook' => 'node',
    'path' => "$core_path/theme/templates",
  );

  $items['tripal_germplasm_base'] = array(
    'variables' => array('node' => NULL),
    'template' => 'tripal_germplasm_base',
    'path' => "$path/theme/templates",
  );

  return $items;
}

/**
 * Implements hook_views_api().
 */
function tripal_germplasm_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'tripal_germplasm') . '/includes',
    'template path' => drupal_get_path('module', 'tripal_germplasm') . '/themes',
  );
}