<?php
/**
 * @class
 * Purpose: Provide a quick search on entity pages which submits/redirects to a full search.
 *
 * Display: A simple textfield search form.
 * Configuration:
 *   - path to the full search.
 *   - the URL token (query parameter) the value applies to.
 *   - help text.
 *   - textfield placeholder.
 *   - search button text.
 *   - autocomplete path.
 */
class local__germ_ril_summary_formatter extends TripalFieldFormatter {
  // The default label for this field.
  public static $default_label = 'Germ RIL Summary';

  // The list of field types for which this formatter is appropriate.
  public static $field_types = array('local__germ_ril_summary');

  /**
   *  Provides the display for a field
   *
   * This function corresponds to the hook_field_formatter_view()
   * function of the Drupal Field API.
   *
   *  This function provides the display for a field when it is viewed on
   *  the web page.  The content returned by the formatter should only include
   *  what is present in the $items[$delta]['values] array. This way, the
   *  contents that are displayed on the page, via webservices and downloaded
   *  into a CSV file will always be identical.  The view need not show all
   *  of the data in the 'values' array.
   *
   *  @param $element
   *  @param $entity_type
   *  @param $entity
   *  @param $langcode
   *  @param $items
   *  @param $display
   *
   *  @return
   *    An element array compatible with that returned by the
   *    hook_field_formatter_view() function.
   */
  public function view(&$element, $entity_type, $entity, $langcode, $items, $display) {
    
        // Style information.
    drupal_add_css(drupal_get_path('module', 'germ_summary') . '/includes/TripalFields/local__germ_ril_summary/theme/style_grs_field.css');

    
    $path = $GLOBALS['base_url'] . '/' . drupal_get_path('module', 'germ_summary') . '/includes/TripalFields/local__germ_ril_summary/theme/';
    
    for($i = 1; $i < 9; $i++) {
      $tbl_args['header'][] = '<img src="' . $path . 'header-f' . $i . '.jpg' . '" alt="' . 'F' . $i . '" title="' . 'F' . $i . '" />';
    }
    
    // RIL Finished header.
    $tbl_args['header'][] = '<img src="' . $path . 'header-finished.jpg' . '" alt="RIL Complete" title="RIL complete" /><small>RIL Complete</small>';
    
    
    
    $tbl_args['rows'][] = array(1,2,3,4,5,6,7,8, 'Complete');
    $tbl_args['attributes'] = array('id' => 'field-germ-ril-summary-table');
    $table = theme('table', $tbl_args);
    
    
    // All set, render items.
    $element[0] = array(
      '#type' => 'markup',
      '#markup' => '<div id="field-germ-ril-summary-wrapper">' . $table  .
        
      '</div>',
    );


    return $element;
  }
}
